/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.rocketmq.a2a.common.model;

/**
 * Encapsulates an A2A (Agent-to-Agent) protocol response message delivered via RocketMQ.
 *
 * <p>This class is used to return results from one agent to another in asynchronous or streaming scenarios.
 * It supports:
 * <ul>
 *   <li>Standard request-response via {@link #responseBody}</li>
 *   <li>Streaming responses using {@link #isStream} and {@link #isEnd} flags</li>
 *   <li>Session correlation via {@link #contextId}</li>
 *   <li>Message acknowledgment via {@link #requestId}</li>
 *   <li>Client-server affinity through {@link #serverLiteTopic} and {@link #serverWorkAgentResponseTopic}</li>
 * </ul>
 *
 * <p><strong>Note:</strong> For streaming responses, multiple {@code RocketMQResponse} messages may be sent,
 * ending with one where {@code isEnd = true}.
 */
public class RocketMQResponse {

    /**
     * Response body content, typically serialized business data (e.g., JSON).
     */
    private String responseBody;

    /**
     * The unique request ID associated with this response, used for correlating the response
     * with its corresponding request. This ID is typically generated by the client when sending
     * the initial A2A request and echoed back in the response for tracking and acknowledgment purposes.
     */
    private String requestId;

    /**
     * Whether this response is part of a streaming sequence.
     */
    private boolean isStream;

    /**
     * Whether this is the final message in a streaming sequence.
     */
    private boolean isEnd;

    /**
     * Context ID, used to associate a complete A2A request-response session.
     */
    private String contextId;

    /**
     * Task ID, which identifies the specific task corresponding to this A2A operation.
     */
    private String taskId;

    /**
     * The response topic used by the server for asynchronous replies.
     * Optional, used for routing follow-up requests.
     */
    private String serverWorkAgentResponseTopic;

    /**
     * The lite topic used by the server to enforce client affinity (sticky session) for subsequent requests
     * of a specific type, ensuring they are routed back to this server instance.
     * <p>
     * A {@code LiteTopic} is a lightweight, runtime-generated session identifier—similar to a {@code SessionId}
     * used for temporary data storage and isolation.
     */
    private String serverLiteTopic;

    /**
     * Default constructor for creating an instance of {@code RocketMQResponse}.
     */
    public RocketMQResponse() {}

    /**
     * Gets the response body content.
     *
     * @return the response body as a string.
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * Sets the response body content.
     *
     * @param responseBody the response body to set
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    /**
     * Gets the unique request ID associated with this response.
     *
     * @return the request ID as a string.
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the unique request ID for this response.
     *
     * @param requestId the request ID to set.
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Checks if this response is part of a streaming sequence.
     *
     * @return {@code true} if it's a streaming response, {@code false} otherwise
     */
    public boolean isStream() {
        return isStream;
    }

    /**
     * Sets whether this response is part of a streaming sequence.
     *
     * @param stream {@code true} to indicate streaming, {@code false} otherwise
     */
    public void setStream(boolean stream) {
        isStream = stream;
    }

    /**
     * Checks if this is the final message in a streaming sequence.
     *
     * @return {@code true} if it's the final message, {@code false} otherwise
     */
    public boolean isEnd() {
        return isEnd;
    }

    /**
     * Sets whether this is the final message in a streaming sequence.
     *
     * @param end {@code true} to indicate the end of the stream, {@code false} otherwise
     */
    public void setEnd(boolean end) {
        isEnd = end;
    }

    /**
     * Gets the context ID for this response.
     *
     * @return the context ID as a string.
     */
    public String getContextId() {
        return contextId;
    }

    /**
     * Sets the context ID for this response.
     *
     * @param contextId the context ID to set
     */
    public void setContextId(String contextId) {
        this.contextId = contextId;
    }

    /**
     * Gets the task ID associated with this response.
     *
     * @return the task ID as a string.
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * Sets the task ID for this response.
     *
     * @param taskId the task ID to set
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * Gets the server work agent response topic.
     *
     * @return the server work agent response topic as a string.
     */
    public String getServerWorkAgentResponseTopic() {
        return serverWorkAgentResponseTopic;
    }

    /**
     * Sets the server work agent response topic.
     *
     * @param serverWorkAgentResponseTopic the topic to set
     */
    public void setServerWorkAgentResponseTopic(String serverWorkAgentResponseTopic) {
        this.serverWorkAgentResponseTopic = serverWorkAgentResponseTopic;
    }

    /**
     * Gets the server lite topic.
     *
     * @return the server lite topic as a string.
     */
    public String getServerLiteTopic() {
        return serverLiteTopic;
    }

    /**
     * Sets the server lite topic.
     *
     * @param serverLiteTopic the lite topic to set.
     */
    public void setServerLiteTopic(String serverLiteTopic) {
        this.serverLiteTopic = serverLiteTopic;
    }

    /**
     * Creates a new builder instance for constructing {@code RocketMQResponse} objects.
     *
     * @return a new {@code Builder} instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for constructing {@code RocketMQResponse} instances.
     */
    public static class Builder {
        private final RocketMQResponse response = new RocketMQResponse();

        /**
         * Sets the response body.
         *
         * @param responseBody the response body to set.
         * @return the current builder instance.
         */
        public Builder responseBody(String responseBody) {
            response.setResponseBody(responseBody);
            return this;
        }

        /**
         * Sets the request ID.
         *
         * @param requestId the request ID to set.
         * @return the current builder instance.
         */
        public Builder requestId(String requestId) {
            response.setRequestId(requestId);
            return this;
        }

        /**
         * Sets whether this is a streaming response.
         *
         * @param stream {@code true} for streaming, {@code false} otherwise.
         * @return the current builder instance.
         */
        public Builder stream(boolean stream) {
            response.setStream(stream);
            return this;
        }

        /**
         * Sets whether this is the final message in a stream.
         *
         * @param end {@code true} to mark the end of the stream, {@code false} otherwise.
         * @return the current builder instance.
         */
        public Builder end(boolean end) {
            response.setEnd(end);
            return this;
        }

        /**
         * Sets the context ID.
         *
         * @param contextId the context ID to set.
         * @return the current builder instance.
         */
        public Builder contextId(String contextId) {
            response.setContextId(contextId);
            return this;
        }

        /**
         * Sets the task ID.
         *
         * @param taskId the task ID to set.
         * @return the current builder instance.
         */
        public Builder taskId(String taskId) {
            response.setTaskId(taskId);
            return this;
        }

        /**
         * Sets the server work agent response topic.
         *
         * @param serverWorkAgentResponseTopic the topic to set.
         * @return the current builder instance.
         */
        public Builder serverWorkAgentResponseTopic(String serverWorkAgentResponseTopic) {
            response.setServerWorkAgentResponseTopic(serverWorkAgentResponseTopic);
            return this;
        }

        /**
         * Sets the server lite topic.
         *
         * @param serverLiteTopic the lite topic to set.
         * @return the current builder instance.
         */
        public Builder serverLiteTopic(String serverLiteTopic) {
            response.setServerLiteTopic(serverLiteTopic);
            return this;
        }

        /**
         * Returns a new {@code RocketMQResponse} object with the configured properties.
         *
         * @return a new RocketMQResponse instance.
         */
        public RocketMQResponse build() {
            return response;
        }
    }

}
