/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.example.controller;

import org.apache.commons.lang3.StringUtils;
import org.example.service.ChatService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;

/**
 * ChatController provides REST endpoints for managing streaming chat interactions
 * using Server-Sent Events (SSE). It supports real-time message streaming,
 * session recovery, offset tracking, and graceful stream closure.
 *
 * <p>This controller is designed to work with a reactive backend ({@link Flux})
 * and is typically used in conjunction with LLM (Large Language Model) applications
 * where incremental token generation needs to be pushed to clients.
 */
@RestController
@RequestMapping("/")
@CrossOrigin(origins = {"http://localhost:9090"})
public class ChatController {
    private static final Logger log = LoggerFactory.getLogger(ChatController.class);

    @Autowired
    ChatService agentService;

    /**
     * Initiates a new streaming chat session.
     *
     * <p>This endpoint starts a real-time stream of text responses (tokens, lines, etc.)
     * generated by the LLM in response to the user's question. The result is returned
     * as a {@link Flux} producing text events over SSE ({@code text/event-stream}).
     *
     * @param question the user's input message or query.
     * @param userId the identifier of the user (defaults to "rocketmq" if not provided).
     * @param sessionId the conversation session ID used for context management.
     * @return a {@link Flux} emitting string chunks incrementally; returns null on error.
     */
    @GetMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<String> streamChat(@RequestParam() String question, @RequestParam(defaultValue = "rocketmq") String userId, @RequestParam() String sessionId) {
        try {
            if (StringUtils.isEmpty(question) || StringUtils.isEmpty(userId) || StringUtils.isEmpty(sessionId)) {
                log.warn("streamChat param error, question: [{}], userId: [{}], sessionId: [{}]", question, userId, sessionId);
                return Flux.error(new IllegalArgumentException("streamChat param error"));
            }
            Flux<String> fluxResult = agentService.streamChat(userId, sessionId, question);
            log.debug("streamChat success, userId: [{}], sessionId: [{}], question: [{}]", userId, sessionId, question);
            return fluxResult;
        } catch (Exception e) {
            log.error("streamChat failed, userId: [{}], sessionId: [{}], question: [{}]", userId, sessionId, question, e);
            return Flux.error(e);
        }
    }

    /**
     * Closes an active streaming session gracefully.
     *
     * <p>This endpoint notifies the server to terminate the ongoing stream for the given
     * user and session, releasing associated resources such as sinks, buffers, or caches.
     * <p>Typically called by the client when navigating away or ending a conversation.
     *
     * @param userId the identifier of the user (defaults to "rocketmq" if not provided).
     * @param sessionId the conversation session ID used for context management.
     * @return {@link ResponseEntity} with "true" if closed successfully, "false" otherwise.
     */
    @GetMapping("/closeStream")
    public ResponseEntity<String> closeStreamChat(@RequestParam(defaultValue = "rocketmq") String userId, @RequestParam String sessionId) {
        try {
            if (StringUtils.isEmpty(userId) || StringUtils.isEmpty(sessionId)) {
                log.warn("closeStreamChat param error, userId: [{}], sessionId: [{}]", userId, sessionId);
                return ResponseEntity.status(400).body("closeStreamChat param is error");
            }
            agentService.closeStreamChat(userId, sessionId);
        } catch (Exception e) {
            log.error("closeStreamChat failed, userId: [{}], sessionId: [{}]", userId, sessionId);
            return ResponseEntity.status(500).body("failed to close stream");
        }
        return ResponseEntity.ok(Boolean.TRUE.toString());
    }

    /**
     * Resumes a previously interrupted chat stream from a specific offset.
     * Allows clients to reconnect and receive only the messages they missed, starting from the last known offset.
     *
     * <p>This is essential for building robust, production-grade streaming experiences
     * that survive temporary disconnections.
     *
     * @param userId the identifier of the user (defaults to "rocketmq" if not provided).
     * @param sessionId the conversation session ID used for context management.
     * @param lastOffset the last received message offset (optional).
     * @return a {@link Flux} emitting messages starting from the specified offset.
     */
    @GetMapping(value = "/resubscribeStream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<String> resubscribeStreamChat(@RequestParam(defaultValue = "rocketmq") String userId, @RequestParam String sessionId, @RequestParam(required = false) Long lastOffset) {
        try {
            if (StringUtils.isEmpty(userId) || StringUtils.isEmpty(sessionId)) {
                log.warn("resubscribeStreamChat param error, userId: [{}], sessionId: [{}]", userId, sessionId);
                return Flux.error(new IllegalArgumentException("resubscribeStreamChat param error"));
            }
            Flux<String> fluxResult = agentService.resubscribeStream(userId, sessionId, lastOffset);
            log.debug("resubscribeStreamChat success, userId: [{}], sessionId: [{}], lastOffset: [{}]", userId, sessionId, lastOffset);
            return fluxResult;
        } catch (Exception e) {
           log.error("resubscribeStreamChat failed, userId: [{}], sessionId: [{}]", userId, sessionId);
           return Flux.error(e);
        }
    }
}
